package model.entity.admin;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 05 19:34:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PolicyViolationEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Policyviolationcode {
            public Object get(PolicyViolationEOImpl obj) {
                return obj.getPolicyviolationcode();
            }

            public void put(PolicyViolationEOImpl obj, Object value) {
                obj.setPolicyviolationcode((String)value);
            }
        }
        ,
        Policyviolationname {
            public Object get(PolicyViolationEOImpl obj) {
                return obj.getPolicyviolationname();
            }

            public void put(PolicyViolationEOImpl obj, Object value) {
                obj.setPolicyviolationname((String)value);
            }
        }
        ,
        Policyviolationtypedesc {
            public Object get(PolicyViolationEOImpl obj) {
                return obj.getPolicyviolationtypedesc();
            }

            public void put(PolicyViolationEOImpl obj, Object value) {
                obj.setPolicyviolationtypedesc((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PolicyViolationEOImpl object);

        public abstract void put(PolicyViolationEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int POLICYVIOLATIONCODE = AttributesEnum.Policyviolationcode.index();
    public static final int POLICYVIOLATIONNAME = AttributesEnum.Policyviolationname.index();
    public static final int POLICYVIOLATIONTYPEDESC = AttributesEnum.Policyviolationtypedesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PolicyViolationEOImpl() {
    }

    /**
     * Gets the attribute value for Policyviolationcode, using the alias name Policyviolationcode.
     * @return the Policyviolationcode
     */
    public String getPolicyviolationcode() {
        return (String)getAttributeInternal(POLICYVIOLATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Policyviolationcode.
     * @param value value to set the Policyviolationcode
     */
    public void setPolicyviolationcode(String value) {
        setAttributeInternal(POLICYVIOLATIONCODE, value);
    }

    /**
     * Gets the attribute value for Policyviolationname, using the alias name Policyviolationname.
     * @return the Policyviolationname
     */
    public String getPolicyviolationname() {
        return (String)getAttributeInternal(POLICYVIOLATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Policyviolationname.
     * @param value value to set the Policyviolationname
     */
    public void setPolicyviolationname(String value) {
        setAttributeInternal(POLICYVIOLATIONNAME, value);
    }

    /**
     * Gets the attribute value for Policyviolationtypedesc, using the alias name Policyviolationtypedesc.
     * @return the Policyviolationtypedesc
     */
    public String getPolicyviolationtypedesc() {
        return (String)getAttributeInternal(POLICYVIOLATIONTYPEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Policyviolationtypedesc.
     * @param value value to set the Policyviolationtypedesc
     */
    public void setPolicyviolationtypedesc(String value) {
        setAttributeInternal(POLICYVIOLATIONTYPEDESC, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param policyviolationcode key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String policyviolationcode) {
        return new Key(new Object[]{policyviolationcode});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.admin.PolicyViolationEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
