package model.am;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 24 14:49:23 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PVDAAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PVDAAppModuleImpl() {
    }

    /**
     * Container's getter for DisciplinaryActionLOV1.
     * @return DisciplinaryActionLOV1
     */
    public ViewObjectImpl getDisciplinaryActionLOV1() {
        return (ViewObjectImpl)findViewObject("DisciplinaryActionLOV1");
    }

    /**
     * Container's getter for DisciplinaryActionTypeLOV1.
     * @return DisciplinaryActionTypeLOV1
     */
    public ViewObjectImpl getDisciplinaryActionTypeLOV1() {
        return (ViewObjectImpl)findViewObject("DisciplinaryActionTypeLOV1");
    }

    /**
     * Container's getter for DisciplinaryActionTypeVO1.
     * @return DisciplinaryActionTypeVO1
     */
    public ViewObjectImpl getDisciplinaryActionTypeVO1() {
        return (ViewObjectImpl)findViewObject("DisciplinaryActionTypeVO1");
    }

    /**
     * Container's getter for EmployeeHRCheckVO1.
     * @return EmployeeHRCheckVO1
     */
    public ViewObjectImpl getEmployeeHRCheckVO1() {
        return (ViewObjectImpl)findViewObject("EmployeeHRCheckVO1");
    }

    /**
     * Container's getter for EmployeeHRLOV1.
     * @return EmployeeHRLOV1
     */
    public ViewObjectImpl getEmployeeHRLOV1() {
        return (ViewObjectImpl)findViewObject("EmployeeHRLOV1");
    }

    /**
     * Container's getter for EmployeeInfoVO1.
     * @return EmployeeInfoVO1
     */
    public ViewObjectImpl getEmployeeInfoVO1() {
        return (ViewObjectImpl)findViewObject("EmployeeInfoVO1");
    }

    /**
     * Container's getter for EmployeeLOV1.
     * @return EmployeeLOV1
     */
    public ViewObjectImpl getEmployeeLOV1() {
        return (ViewObjectImpl)findViewObject("EmployeeLOV1");
    }

    /**
     * Container's getter for GetEmployeeHRVO1.
     * @return GetEmployeeHRVO1
     */
    public ViewObjectImpl getGetEmployeeHRVO1() {
        return (ViewObjectImpl)findViewObject("GetEmployeeHRVO1");
    }

    /**
     * Container's getter for IncidentReportedByLOV1.
     * @return IncidentReportedByLOV1
     */
    public ViewObjectImpl getIncidentReportedByLOV1() {
        return (ViewObjectImpl)findViewObject("IncidentReportedByLOV1");
    }

    /**
     * Container's getter for IncidentReportVO1.
     * @return IncidentReportVO1
     */
    public ViewObjectImpl getIncidentReportVO1() {
        return (ViewObjectImpl)findViewObject("IncidentReportVO1");
    }

    /**
     * Container's getter for ReportingManagerLOV1.
     * @return ReportingManagerLOV1
     */
    public ViewObjectImpl getReportingManagerLOV1() {
        return (ViewObjectImpl)findViewObject("ReportingManagerLOV1");
    }

    /**
     * Container's getter for StatusLOV1.
     * @return StatusLOV1
     */
    public ViewObjectImpl getStatusLOV1() {
        return (ViewObjectImpl)findViewObject("StatusLOV1");
    }
    
    /**
     * Method to set the session values in userdata.
     * @param session Session
     */
    protected void prepareSession(Session session){
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String sess ="1";
    //        Integer loginId = Integer.valueOf(sess);
    //        Number loginUserId = (Number)loginId;
    //        System.out.println("loginUserId: "+loginUserId);
        this.getSession().getUserData().put("loginUserId",sess);
       //this.getSession().getUserData().put("loginUserId",1);
        super.prepareSession(session);
    }

    /**
     * Container's getter for ManagerIncidentReportVO1.
     * @return ManagerIncidentReportVO1
     */
    public ViewObjectImpl getManagerIncidentReportVO1() {
        return (ViewObjectImpl)findViewObject("ManagerIncidentReportVO1");
    }

    /**
     * Container's getter for PolicyViolationLOV1.
     * @return PolicyViolationLOV1
     */
    public ViewObjectImpl getPolicyViolationLOV1() {
        return (ViewObjectImpl)findViewObject("PolicyViolationLOV1");
    }

    /**
     * Container's getter for PolicyViolationVO1.
     * @return PolicyViolationVO1
     */
    public ViewObjectImpl getPolicyViolationVO1() {
        return (ViewObjectImpl)findViewObject("PolicyViolationVO1");
    }

    /**
     * Container's getter for DisciplinaryActionTypeVO2.
     * @return DisciplinaryActionTypeVO2
     */
    public ViewObjectImpl getDisciplinaryActionTypeVO2() {
        return (ViewObjectImpl)findViewObject("DisciplinaryActionTypeVO2");
    }

    /**
     * Container's getter for PolicyViolationVO2.
     * @return PolicyViolationVO2
     */
    public ViewObjectImpl getPolicyViolationVO2() {
        return (ViewObjectImpl)findViewObject("PolicyViolationVO2");
    }

    /**
     * Container's getter for EmployeeVO1.
     * @return EmployeeVO1
     */
    public ViewObjectImpl getEmployeeVO1() {
        return (ViewObjectImpl)findViewObject("EmployeeVO1");
    }

    /**
     * Container's getter for EmployeeVO2.
     * @return EmployeeVO2
     */
    public ViewObjectImpl getEmployeeVOvialink() {
        return (ViewObjectImpl)findViewObject("EmployeeVOvialink");
    }

    /**
     * Container's getter for EmployeeFk2Link1.
     * @return EmployeeFk2Link1
     */
    public ViewLinkImpl getEmployeeFk2Link1() {
        return (ViewLinkImpl)findViewLink("EmployeeFk2Link1");
    }

    /**
     * Container's getter for YesNoVO1.
     * @return YesNoVO1
     */
    public ViewObjectImpl getYesNoVO1() {
        return (ViewObjectImpl)findViewObject("YesNoVO1");
    }
}
